# Generated by Django 4.1.2 on 2022-10-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_delete_alter_users_nome_alter_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='delete',
        ),
    ]
