# Generated by Django 4.1.2 on 2022-10-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_users_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
