# Generated by Django 4.1.2 on 2022-10-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_deleted_at_users_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_delete',
        ),
    ]
