# Generated by Django 4.1.2 on 2022-10-08 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('subnome', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('tags', models.CharField(max_length=2000)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
