# Generated by Django 4.1.2 on 2022-10-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0002_alter_experiencias_options_experiencias_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencias',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
